[package]
name = "tower-timeout"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.1.0"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-timeout/0.1.0"
description = """
Apply a timeout to requests, ensuring completion within a fixed time duration.
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"

[dependencies]
# futures = "0.1.26"
# tower-service = "0.2.0"
tower-service = { path = "../tower-service" }
tower-layer = { path = "../tower-layer" }
# tokio-timer = "0.2.6"
tokio-timer = { git = "https://github.com/tokio-rs/tokio", branch = "std-future" }

[dev-dependencies]
futures-preview = "0.3.0-alpha.16"
pin-utils = "0.1.0-alpha.4"
tokio = { git = "https://github.com/tokio-rs/tokio" }