parameters:
  crates: []

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: azure-is-release.yml

  - ${{ each crate in parameters.crates }}:
    - script: cargo test
      env:
        CI: 'True'
      displayName: cargo test -p ${{ crate }}
      workingDirectory: $(Build.SourcesDirectory)/${{ crate }}
      condition: and(succeeded(), not(variables['isRelease']))

  - template: azure-patch-crates.yml

  - ${{ each crate in parameters.crates }}:
    - script: cargo test
      env:
        CI: 'True'
      displayName: cargo test -p ${{ crate }}
      workingDirectory: $(Build.SourcesDirectory)/${{ crate }}
